#!/usr/bin/env just --justfile

set fallback

dev:
	just ../dev/auth-key
	bun wrangler d1 migrations apply DB --local
	bun wrangler dev --var "RELAY_SECRET:$(cat ../dev/root.jwk)" --var "RELAY_URL:http://${TAURI_DEV_HOST:-localhost}:4443"

build:
	bun run build

check:
	bun exec biome check
	bun tsc --noEmit
	#bun exec madge --circular --extensions ts,tsx src

fix:
	bun wrangler types

deploy: build
	bun wrangler d1 migrations apply DB --env live --remote
	bun wrangler deploy --env live
